# Form implementation generated from reading ui file 'UI_file\base_screen.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 300)
        self.name_line = QtWidgets.QLineEdit(parent=Dialog)
        self.name_line.setGeometry(QtCore.QRect(180, 80, 113, 21))
        self.name_line.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.name_line.setObjectName("name_line")
        self.password_line = QtWidgets.QLineEdit(parent=Dialog)
        self.password_line.setGeometry(QtCore.QRect(180, 140, 113, 21))
        self.password_line.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_line.setObjectName("password_line")
        self.login_pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.login_pushButton.setGeometry(QtCore.QRect(90, 220, 93, 28))
        self.login_pushButton.setObjectName("login_pushButton")
        self.sign_pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.sign_pushButton_2.setGeometry(QtCore.QRect(260, 220, 93, 28))
        self.sign_pushButton_2.setObjectName("sign_pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.name_line.setPlaceholderText(_translate("Dialog", "请输入名字>>>"))
        self.password_line.setPlaceholderText(_translate("Dialog", "请输入密码>>>"))
        self.login_pushButton.setText(_translate("Dialog", "PushButton"))
        self.sign_pushButton_2.setText(_translate("Dialog", "PushButton"))
