# Form implementation generated from reading ui file 'e:\Learning_pyqt6\UI_file\AddBook.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 600)
        Dialog.setMinimumSize(QtCore.QSize(500, 600))
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: #f0f2f5;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    color: #262626;\n"
"}\n"
"\n"
"QLineEdit, QDoubleSpinBox, QSpinBox, QDateEdit {\n"
"    padding: 8px;\n"
"    border: 1px solid #d9d9d9;\n"
"    border-radius: 4px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus, QDoubleSpinBox:focus, QSpinBox:focus, QDateEdit:focus {\n"
"    border-color: #40a9ff;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit:hover, QDoubleSpinBox:hover, QSpinBox:hover, QDateEdit:hover {\n"
"    border-color: #40a9ff;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    padding: 8px;\n"
"    border: 1px solid #d9d9d9;\n"
"    border-radius: 4px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border-color: #40a9ff;\n"
"    outline: none;\n"
"}\n"
"\n"
"QTextEdit:hover {\n"
"    border-color: #40a9ff;\n"
"}\n"
"\n"
"QScrollArea {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f0f0f0;\n"
"    width: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #d9d9d9;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #bfbfbf;\n"
"}\n"
"\n"
"QPushButton {\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    min-width: 100px;\n"
"    min-height: 35px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=Dialog)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.scrollArea = QtWidgets.QScrollArea(parent=Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 480, 500))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.bookTitleLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.bookTitleLabel.setObjectName("bookTitleLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.bookTitleLabel)
        self.bookTitleEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.bookTitleEdit.setObjectName("bookTitleEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.bookTitleEdit)
        self.authorLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.authorLabel.setObjectName("authorLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.authorLabel)
        self.authorEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.authorEdit.setObjectName("authorEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.authorEdit)
        self.locationLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.locationLabel.setObjectName("locationLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.locationLabel)
        self.locationEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.locationEdit.setObjectName("locationEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.locationEdit)
        self.originalPriceLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.originalPriceLabel.setObjectName("originalPriceLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.originalPriceLabel)
        self.originalPriceSpinBox = QtWidgets.QDoubleSpinBox(parent=self.scrollAreaWidgetContents)
        self.originalPriceSpinBox.setDecimals(2)
        self.originalPriceSpinBox.setMaximum(9999.99)
        self.originalPriceSpinBox.setObjectName("originalPriceSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.originalPriceSpinBox)
        self.publicationYearLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.publicationYearLabel.setObjectName("publicationYearLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.publicationYearLabel)
        self.publicationYearSpinBox = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.publicationYearSpinBox.setMinimum(1900)
        self.publicationYearSpinBox.setMaximum(2030)
        self.publicationYearSpinBox.setProperty("value", 2023)
        self.publicationYearSpinBox.setObjectName("publicationYearSpinBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.publicationYearSpinBox)
        self.publisherLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.publisherLabel.setObjectName("publisherLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.publisherLabel)
        self.publisherEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.publisherEdit.setObjectName("publisherEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.publisherEdit)
        self.quantityLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.quantityLabel.setObjectName("quantityLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.quantityLabel)
        self.quantitySpinBox = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.quantitySpinBox.setMinimum(1)
        self.quantitySpinBox.setMaximum(999)
        self.quantitySpinBox.setProperty("value", 1)
        self.quantitySpinBox.setObjectName("quantitySpinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.quantitySpinBox)
        self.purchaseDateLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.purchaseDateLabel.setObjectName("purchaseDateLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.purchaseDateLabel)
        self.purchaseDateEdit = QtWidgets.QDateEdit(parent=self.scrollAreaWidgetContents)
        self.purchaseDateEdit.setCalendarPopup(True)
        self.purchaseDateEdit.setDate(QtCore.QDate(2023, 10, 1))
        self.purchaseDateEdit.setObjectName("purchaseDateEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.purchaseDateEdit)
        self.purchasePriceLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.purchasePriceLabel.setObjectName("purchasePriceLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.purchasePriceLabel)
        self.purchasePriceSpinBox = QtWidgets.QDoubleSpinBox(parent=self.scrollAreaWidgetContents)
        self.purchasePriceSpinBox.setDecimals(2)
        self.purchasePriceSpinBox.setMaximum(9999.99)
        self.purchasePriceSpinBox.setObjectName("purchasePriceSpinBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.purchasePriceSpinBox)
        self.notesLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.notesLabel.setObjectName("notesLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.notesLabel)
        self.notesEdit = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents)
        self.notesEdit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.notesEdit.setObjectName("notesEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.notesEdit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.confirmButton = QtWidgets.QPushButton(parent=Dialog)
        self.confirmButton.setObjectName("confirmButton")
        self.buttonLayout.addWidget(self.confirmButton)
        self.cancelButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "添加图书"))
        self.titleLabel.setText(_translate("Dialog", "添加新图书"))
        self.titleLabel.setStyleSheet(_translate("Dialog", "font-size: 24px; font-weight: bold; color: #1890ff; margin: 10px;"))
        self.bookTitleLabel.setText(_translate("Dialog", "书名 *:"))
        self.bookTitleEdit.setPlaceholderText(_translate("Dialog", "请输入书名"))
        self.authorLabel.setText(_translate("Dialog", "作者:"))
        self.authorEdit.setPlaceholderText(_translate("Dialog", "请输入作者"))
        self.locationLabel.setText(_translate("Dialog", "存放位置:"))
        self.locationEdit.setPlaceholderText(_translate("Dialog", "请输入存放位置"))
        self.originalPriceLabel.setText(_translate("Dialog", "原价:"))
        self.originalPriceSpinBox.setSuffix(_translate("Dialog", " 元"))
        self.publicationYearLabel.setText(_translate("Dialog", "出版年份:"))
        self.publisherLabel.setText(_translate("Dialog", "出版社:"))
        self.publisherEdit.setPlaceholderText(_translate("Dialog", "请输入出版社"))
        self.quantityLabel.setText(_translate("Dialog", "数量:"))
        self.purchaseDateLabel.setText(_translate("Dialog", "购买日期:"))
        self.purchasePriceLabel.setText(_translate("Dialog", "购买价格:"))
        self.purchasePriceSpinBox.setSuffix(_translate("Dialog", " 元"))
        self.notesLabel.setText(_translate("Dialog", "备注:"))
        self.notesEdit.setPlaceholderText(_translate("Dialog", "请输入备注信息"))
        self.confirmButton.setStyleSheet(_translate("Dialog", "QPushButton {\n"
"    background-color: #52c41a;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #73d13d;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #389e0d;\n"
"}"))
        self.confirmButton.setText(_translate("Dialog", "确认添加"))
        self.cancelButton.setStyleSheet(_translate("Dialog", "QPushButton {\n"
"    background-color: #ff4d4f;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff7875;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9363e;\n"
"}"))
        self.cancelButton.setText(_translate("Dialog", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
