# Form implementation generated from reading ui file 'UI_file\Login_Window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.Initial_Login_Botton = QtWidgets.QPushButton(parent=Dialog)
        self.Initial_Login_Botton.setGeometry(QtCore.QRect(110, 210, 75, 24))
        self.Initial_Login_Botton.setObjectName("Initial_Login_Botton")
        self.Initial_Register_Botton = QtWidgets.QPushButton(parent=Dialog)
        self.Initial_Register_Botton.setGeometry(QtCore.QRect(215, 210, 75, 24))
        self.Initial_Register_Botton.setObjectName("Initial_Register_Botton")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(110, 61, 181, 71))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.Initial_name_input = QtWidgets.QLineEdit(parent=self.widget)
        self.Initial_name_input.setObjectName("Initial_name_input")
        self.horizontalLayout.addWidget(self.Initial_name_input)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.Initial_password_input = QtWidgets.QLineEdit(parent=self.widget)
        self.Initial_password_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Initial_password_input.setObjectName("Initial_password_input")
        self.horizontalLayout_2.addWidget(self.Initial_password_input)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "登录"))
        self.Initial_Login_Botton.setText(_translate("Dialog", "登录"))
        self.Initial_Register_Botton.setText(_translate("Dialog", "注册"))
        self.label.setText(_translate("Dialog", "名字"))
        self.label_2.setText(_translate("Dialog", "密码"))
