# Form implementation generated from reading ui file 'e:\Learning_pyqt6\UI_file\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #f0f2f5;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #1890ff;\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"    padding: 5px 15px;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #40a9ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #096dd9;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #d9d9d9;\n"
"    border-radius: 4px;\n"
"    gridline-color: #f0f0f0;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #e6f7ff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #fafafa;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    border-right: 1px solid #f0f0f0;\n"
"    border-bottom: 1px solid #f0f0f0;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f0f0f0;\n"
"    width: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #d9d9d9;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #bfbfbf;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #ffffff;\n"
"    border-bottom: 1px solid #f0f0f0;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background-color: #ffffff;\n"
"    border-top: 1px solid #f0f0f0;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bookTable = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.bookTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.bookTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.bookTable.setAlternatingRowColors(True)
        self.bookTable.setObjectName("bookTable")
        self.bookTable.setColumnCount(10)
        self.bookTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.bookTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.bookTable.setHorizontalHeaderItem(9, item)
        self.bookTable.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.bookTable)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.setMinimumSize(QtCore.QSize(120, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addButton.setIcon(icon)
        self.addButton.setObjectName("addButton")
        self.verticalLayout.addWidget(self.addButton)
        self.deleteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteButton.setMinimumSize(QtCore.QSize(120, 40))
        self.deleteButton.setStyleSheet("QPushButton {\n"
"    background-color: #ff4d4f;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff7875;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d9363e;\n"
"}")
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout.addWidget(self.deleteButton)
        self.searchButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.searchButton.setMinimumSize(QtCore.QSize(120, 40))
        self.searchButton.setStyleSheet("QPushButton {\n"
"    background-color: #52c41a;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #73d13d;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #389e0d;\n"
"}")
        self.searchButton.setObjectName("searchButton")
        self.verticalLayout.addWidget(self.searchButton)
        self.updateButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.updateButton.setMinimumSize(QtCore.QSize(120, 40))
        self.updateButton.setStyleSheet("QPushButton {\n"
"    background-color: #faad14;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffc53d;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d48806;\n"
"}")
        self.updateButton.setObjectName("updateButton")
        self.verticalLayout.addWidget(self.updateButton)
        self.exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitButton.setMinimumSize(QtCore.QSize(120, 40))
        self.exitButton.setStyleSheet("QPushButton {\n"
"    background-color: #8c8c8c;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a6a6a6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #737373;\n"
"}")
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout.addWidget(self.exitButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图书管理系统"))
        self.bookTable.setSortingEnabled(True)
        item = self.bookTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "书名"))
        item = self.bookTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "作者"))
        item = self.bookTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "存放位置"))
        item = self.bookTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "原价"))
        item = self.bookTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "出版年份"))
        item = self.bookTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "出版社"))
        item = self.bookTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "数量"))
        item = self.bookTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "购买日期"))
        item = self.bookTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "购买价格"))
        item = self.bookTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "备注"))
        self.addButton.setText(_translate("MainWindow", "添加图书"))
        self.deleteButton.setText(_translate("MainWindow", "删除图书"))
        self.searchButton.setText(_translate("MainWindow", "查询图书"))
        self.updateButton.setText(_translate("MainWindow", "更新图书"))
        self.exitButton.setText(_translate("MainWindow", "退出系统"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
