# Form implementation generated from reading ui file 'e:\Learning_pyqt6\UI_file\SearchWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(600, 400))
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: #f0f2f5;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    padding: 8px 12px;\n"
"    border: 2px solid #d9d9d9;\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #40a9ff;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #40a9ff;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    padding: 12px;\n"
"    border: 1px solid #d9d9d9;\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"    line-height: 1.5;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border-color: #40a9ff;\n"
"    outline: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f0f0f0;\n"
"    width: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #d9d9d9;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #bfbfbf;\n"
"}\n"
"\n"
"QPushButton {\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    min-width: 80px;\n"
"    min-height: 35px;\n"
"}\n"
"\n"
"QPushButton#searchButton {\n"
"    background-color: #1890ff;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#searchButton:hover {\n"
"    background-color: #40a9ff;\n"
"}\n"
"\n"
"QPushButton#searchButton:pressed {\n"
"    background-color: #096dd9;\n"
"}\n"
"\n"
"QPushButton#clearButton {\n"
"    background-color: #ff4d4f;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#clearButton:hover {\n"
"    background-color: #ff7875;\n"
"}\n"
"\n"
"QPushButton#clearButton:pressed {\n"
"    background-color: #d9363e;\n"
"}\n"
"\n"
"QPushButton#closeButton {\n"
"    background-color: #8c8c8c;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#closeButton:hover {\n"
"    background-color: #a6a6a6;\n"
"}\n"
"\n"
"QPushButton#closeButton:pressed {\n"
"    background-color: #595959;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setSpacing(10)
        self.searchLayout.setObjectName("searchLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.searchLineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.searchLayout.addWidget(self.searchLineEdit)
        self.searchButton = QtWidgets.QPushButton(parent=Dialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("e:\\Learning_pyqt6\\UI_file\\icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.searchButton.setIcon(icon)
        self.searchButton.setObjectName("searchButton")
        self.searchLayout.addWidget(self.searchButton)
        self.verticalLayout_2.addLayout(self.searchLayout)
        self.resultTextEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.resultTextEdit.setReadOnly(True)
        self.resultTextEdit.setObjectName("resultTextEdit")
        self.verticalLayout_2.addWidget(self.resultTextEdit)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(10)
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.clearButton = QtWidgets.QPushButton(parent=Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("e:\\Learning_pyqt6\\UI_file\\icons/clear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.clearButton.setIcon(icon1)
        self.clearButton.setObjectName("clearButton")
        self.buttonLayout.addWidget(self.clearButton)
        self.closeButton = QtWidgets.QPushButton(parent=Dialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("e:\\Learning_pyqt6\\UI_file\\icons/close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.closeButton.setIcon(icon2)
        self.closeButton.setObjectName("closeButton")
        self.buttonLayout.addWidget(self.closeButton)
        self.verticalLayout_2.addLayout(self.buttonLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "查找书籍"))
        self.searchLineEdit.setPlaceholderText(_translate("Dialog", "请输入书名、作者、出版社等关键词进行搜索"))
        self.searchButton.setText(_translate("Dialog", "查找"))
        self.resultTextEdit.setPlaceholderText(_translate("Dialog", "搜索结果将显示在这里..."))
        self.clearButton.setText(_translate("Dialog", "清空"))
        self.closeButton.setText(_translate("Dialog", "关闭"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
