# Form implementation generated from reading ui file 'e:\Learning_pyqt6\UI_file\UpdateBookWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 600)
        Dialog.setMinimumSize(QtCore.QSize(500, 600))
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: #f0f2f5;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    color: #262626;\n"
"}\n"
"\n"
"QLineEdit, QDoubleSpinBox, QSpinBox, QDateEdit {\n"
"    padding: 8px;\n"
"    border: 1px solid #d9d9d9;\n"
"    border-radius: 4px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus, QDoubleSpinBox:focus, QSpinBox:focus, QDateEdit:focus {\n"
"    border-color: #40a9ff;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit:hover, QDoubleSpinBox:hover, QSpinBox:hover, QDateEdit:hover {\n"
"    border-color: #40a9ff;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    padding: 8px;\n"
"    border: 1px solid #d9d9d9;\n"
"    border-radius: 4px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border-color: #40a9ff;\n"
"    outline: none;\n"
"}\n"
"\n"
"QTextEdit:hover {\n"
"    border-color: #40a9ff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    min-width: 100px;\n"
"    min-height: 35px;\n"
"}\n"
"\n"
"QPushButton#confirmButton {\n"
"    background-color: #52c41a;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#confirmButton:hover {\n"
"    background-color: #73d13d;\n"
"}\n"
"\n"
"QPushButton#confirmButton:pressed {\n"
"    background-color: #389e0d;\n"
"}\n"
"\n"
"QPushButton#cancelButton {\n"
"    background-color: #ff4d4f;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#cancelButton:hover {\n"
"    background-color: #ff7875;\n"
"}\n"
"\n"
"QPushButton#cancelButton:pressed {\n"
"    background-color: #d9363e;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=Dialog)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.titleLabel1 = QtWidgets.QLabel(parent=Dialog)
        self.titleLabel1.setObjectName("titleLabel1")
        self.gridLayout.addWidget(self.titleLabel1, 0, 0, 1, 1)
        self.bookTitleEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.bookTitleEdit.setObjectName("bookTitleEdit")
        self.gridLayout.addWidget(self.bookTitleEdit, 0, 1, 1, 1)
        self.authorLabel = QtWidgets.QLabel(parent=Dialog)
        self.authorLabel.setObjectName("authorLabel")
        self.gridLayout.addWidget(self.authorLabel, 0, 2, 1, 1)
        self.authorEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.authorEdit.setObjectName("authorEdit")
        self.gridLayout.addWidget(self.authorEdit, 0, 3, 1, 1)
        self.locationLabel = QtWidgets.QLabel(parent=Dialog)
        self.locationLabel.setObjectName("locationLabel")
        self.gridLayout.addWidget(self.locationLabel, 1, 0, 1, 1)
        self.locationEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.locationEdit.setObjectName("locationEdit")
        self.gridLayout.addWidget(self.locationEdit, 1, 1, 1, 1)
        self.originalPriceLabel = QtWidgets.QLabel(parent=Dialog)
        self.originalPriceLabel.setObjectName("originalPriceLabel")
        self.gridLayout.addWidget(self.originalPriceLabel, 1, 2, 1, 1)
        self.originalPriceSpinBox = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.originalPriceSpinBox.setMaximum(99999.99)
        self.originalPriceSpinBox.setSingleStep(0.01)
        self.originalPriceSpinBox.setObjectName("originalPriceSpinBox")
        self.gridLayout.addWidget(self.originalPriceSpinBox, 1, 3, 1, 1)
        self.publicationYearLabel = QtWidgets.QLabel(parent=Dialog)
        self.publicationYearLabel.setObjectName("publicationYearLabel")
        self.gridLayout.addWidget(self.publicationYearLabel, 2, 0, 1, 1)
        self.publicationYearSpinBox = QtWidgets.QSpinBox(parent=Dialog)
        self.publicationYearSpinBox.setMinimum(1900)
        self.publicationYearSpinBox.setMaximum(2030)
        self.publicationYearSpinBox.setProperty("value", 2024)
        self.publicationYearSpinBox.setObjectName("publicationYearSpinBox")
        self.gridLayout.addWidget(self.publicationYearSpinBox, 2, 1, 1, 1)
        self.publisherLabel = QtWidgets.QLabel(parent=Dialog)
        self.publisherLabel.setObjectName("publisherLabel")
        self.gridLayout.addWidget(self.publisherLabel, 2, 2, 1, 1)
        self.publisherEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.publisherEdit.setObjectName("publisherEdit")
        self.gridLayout.addWidget(self.publisherEdit, 2, 3, 1, 1)
        self.quantityLabel = QtWidgets.QLabel(parent=Dialog)
        self.quantityLabel.setObjectName("quantityLabel")
        self.gridLayout.addWidget(self.quantityLabel, 3, 0, 1, 1)
        self.quantitySpinBox = QtWidgets.QSpinBox(parent=Dialog)
        self.quantitySpinBox.setMinimum(1)
        self.quantitySpinBox.setMaximum(999)
        self.quantitySpinBox.setProperty("value", 1)
        self.quantitySpinBox.setObjectName("quantitySpinBox")
        self.gridLayout.addWidget(self.quantitySpinBox, 3, 1, 1, 1)
        self.purchaseDateLabel = QtWidgets.QLabel(parent=Dialog)
        self.purchaseDateLabel.setObjectName("purchaseDateLabel")
        self.gridLayout.addWidget(self.purchaseDateLabel, 3, 2, 1, 1)
        self.purchaseDateEdit = QtWidgets.QDateEdit(parent=Dialog)
        self.purchaseDateEdit.setCalendarPopup(True)
        self.purchaseDateEdit.setDate(QtCore.QDate(2024, 1, 1))
        self.purchaseDateEdit.setObjectName("purchaseDateEdit")
        self.gridLayout.addWidget(self.purchaseDateEdit, 3, 3, 1, 1)
        self.purchasePriceLabel = QtWidgets.QLabel(parent=Dialog)
        self.purchasePriceLabel.setObjectName("purchasePriceLabel")
        self.gridLayout.addWidget(self.purchasePriceLabel, 4, 0, 1, 1)
        self.purchasePriceSpinBox = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.purchasePriceSpinBox.setMaximum(99999.99)
        self.purchasePriceSpinBox.setSingleStep(0.01)
        self.purchasePriceSpinBox.setObjectName("purchasePriceSpinBox")
        self.gridLayout.addWidget(self.purchasePriceSpinBox, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.notesLabel = QtWidgets.QLabel(parent=Dialog)
        self.notesLabel.setObjectName("notesLabel")
        self.verticalLayout.addWidget(self.notesLabel)
        self.notesEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.notesEdit.setMaximumSize(QtCore.QSize(16777215, 120))
        self.notesEdit.setObjectName("notesEdit")
        self.verticalLayout.addWidget(self.notesEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(10)
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.confirmButton = QtWidgets.QPushButton(parent=Dialog)
        self.confirmButton.setObjectName("confirmButton")
        self.buttonLayout.addWidget(self.confirmButton)
        self.cancelButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "更新书籍"))
        self.titleLabel.setText(_translate("Dialog", "更新图书信息"))
        self.titleLabel.setStyleSheet(_translate("Dialog", "font-size: 24px; font-weight: bold; color: #1890ff; margin: 10px;"))
        self.titleLabel1.setText(_translate("Dialog", "书名:"))
        self.bookTitleEdit.setPlaceholderText(_translate("Dialog", "请输入书名"))
        self.authorLabel.setText(_translate("Dialog", "作者:"))
        self.authorEdit.setPlaceholderText(_translate("Dialog", "请输入作者"))
        self.locationLabel.setText(_translate("Dialog", "存放位置:"))
        self.locationEdit.setPlaceholderText(_translate("Dialog", "请输入存放位置"))
        self.originalPriceLabel.setText(_translate("Dialog", "原价:"))
        self.originalPriceSpinBox.setSuffix(_translate("Dialog", " 元"))
        self.publicationYearLabel.setText(_translate("Dialog", "出版年份:"))
        self.publisherLabel.setText(_translate("Dialog", "出版社:"))
        self.publisherEdit.setPlaceholderText(_translate("Dialog", "请输入出版社"))
        self.quantityLabel.setText(_translate("Dialog", "数量:"))
        self.purchaseDateLabel.setText(_translate("Dialog", "购买日期:"))
        self.purchasePriceLabel.setText(_translate("Dialog", "购买价格:"))
        self.purchasePriceSpinBox.setSuffix(_translate("Dialog", " 元"))
        self.notesLabel.setText(_translate("Dialog", "备注:"))
        self.notesEdit.setPlaceholderText(_translate("Dialog", "请输入备注信息"))
        self.confirmButton.setText(_translate("Dialog", "确认更新"))
        self.cancelButton.setText(_translate("Dialog", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
