from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.titleLabel = QtWidgets.QLabel(parent=Dialog)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 0, 0, 1, 1)
        self.bookTitleEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.bookTitleEdit.setObjectName("bookTitleEdit")
        self.gridLayout.addWidget(self.bookTitleEdit, 0, 1, 1, 1)
        self.authorLabel = QtWidgets.QLabel(parent=Dialog)
        self.authorLabel.setObjectName("authorLabel")
        self.gridLayout.addWidget(self.authorLabel, 0, 2, 1, 1)
        self.authorEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.authorEdit.setObjectName("authorEdit")
        self.gridLayout.addWidget(self.authorEdit, 0, 3, 1, 1)
        self.locationLabel = QtWidgets.QLabel(parent=Dialog)
        self.locationLabel.setObjectName("locationLabel")
        self.gridLayout.addWidget(self.locationLabel, 1, 0, 1, 1)
        self.locationEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.locationEdit.setObjectName("locationEdit")
        self.gridLayout.addWidget(self.locationEdit, 1, 1, 1, 1)
        self.originalPriceLabel = QtWidgets.QLabel(parent=Dialog)
        self.originalPriceLabel.setObjectName("originalPriceLabel")
        self.gridLayout.addWidget(self.originalPriceLabel, 1, 2, 1, 1)
        self.originalPriceSpinBox = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.originalPriceSpinBox.setMaximum(99999.99)
        self.originalPriceSpinBox.setSingleStep(0.01)
        self.originalPriceSpinBox.setObjectName("originalPriceSpinBox")
        self.gridLayout.addWidget(self.originalPriceSpinBox, 1, 3, 1, 1)
        self.publicationYearLabel = QtWidgets.QLabel(parent=Dialog)
        self.publicationYearLabel.setObjectName("publicationYearLabel")
        self.gridLayout.addWidget(self.publicationYearLabel, 2, 0, 1, 1)
        self.publicationYearSpinBox = QtWidgets.QSpinBox(parent=Dialog)
        self.publicationYearSpinBox.setMinimum(1000)
        self.publicationYearSpinBox.setMaximum(9999)
        self.publicationYearSpinBox.setProperty("value", 2024)
        self.publicationYearSpinBox.setObjectName("publicationYearSpinBox")
        self.gridLayout.addWidget(self.publicationYearSpinBox, 2, 1, 1, 1)
        self.publisherLabel = QtWidgets.QLabel(parent=Dialog)
        self.publisherLabel.setObjectName("publisherLabel")
        self.gridLayout.addWidget(self.publisherLabel, 2, 2, 1, 1)
        self.publisherEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.publisherEdit.setObjectName("publisherEdit")
        self.gridLayout.addWidget(self.publisherEdit, 2, 3, 1, 1)
        self.quantityLabel = QtWidgets.QLabel(parent=Dialog)
        self.quantityLabel.setObjectName("quantityLabel")
        self.gridLayout.addWidget(self.quantityLabel, 3, 0, 1, 1)
        self.quantitySpinBox = QtWidgets.QSpinBox(parent=Dialog)
        self.quantitySpinBox.setMinimum(1)
        self.quantitySpinBox.setMaximum(9999)
        self.quantitySpinBox.setProperty("value", 1)
        self.quantitySpinBox.setObjectName("quantitySpinBox")
        self.gridLayout.addWidget(self.quantitySpinBox, 3, 1, 1, 1)
        self.purchaseDateLabel = QtWidgets.QLabel(parent=Dialog)
        self.purchaseDateLabel.setObjectName("purchaseDateLabel")
        self.gridLayout.addWidget(self.purchaseDateLabel, 3, 2, 1, 1)
        self.purchaseDateEdit = QtWidgets.QDateEdit(parent=Dialog)
        self.purchaseDateEdit.setCalendarPopup(True)
        self.purchaseDateEdit.setDate(QtCore.QDate(2024, 1, 1))
        self.purchaseDateEdit.setObjectName("purchaseDateEdit")
        self.gridLayout.addWidget(self.purchaseDateEdit, 3, 3, 1, 1)
        self.purchasePriceLabel = QtWidgets.QLabel(parent=Dialog)
        self.purchasePriceLabel.setObjectName("purchasePriceLabel")
        self.gridLayout.addWidget(self.purchasePriceLabel, 4, 0, 1, 1)
        self.purchasePriceSpinBox = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.purchasePriceSpinBox.setMaximum(99999.99)
        self.purchasePriceSpinBox.setSingleStep(0.01)
        self.purchasePriceSpinBox.setObjectName("purchasePriceSpinBox")
        self.gridLayout.addWidget(self.purchasePriceSpinBox, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.notesLabel = QtWidgets.QLabel(parent=Dialog)
        self.notesLabel.setObjectName("notesLabel")
        self.verticalLayout.addWidget(self.notesLabel)
        self.notesEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.notesEdit.setMaximumSize(QtCore.QSize(16777215, 120))
        self.notesEdit.setObjectName("notesEdit")
        self.verticalLayout.addWidget(self.notesEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.confirmButton = QtWidgets.QPushButton(parent=Dialog)
        self.confirmButton.setMinimumSize(QtCore.QSize(100, 35))
        self.confirmButton.setObjectName("confirmButton")
        self.buttonLayout.addWidget(self.confirmButton)
        self.cancelButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancelButton.setMinimumSize(QtCore.QSize(100, 35))
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "更新书籍"))
        self.titleLabel.setText(_translate("Dialog", "书名:"))
        self.authorLabel.setText(_translate("Dialog", "作者:"))
        self.locationLabel.setText(_translate("Dialog", "存放位置:"))
        self.originalPriceLabel.setText(_translate("Dialog", "原价:"))
        self.publicationYearLabel.setText(_translate("Dialog", "出版年份:"))
        self.publisherLabel.setText(_translate("Dialog", "出版社:"))
        self.quantityLabel.setText(_translate("Dialog", "数量:"))
        self.purchaseDateLabel.setText(_translate("Dialog", "购买日期:"))
        self.purchasePriceLabel.setText(_translate("Dialog", "购买价格:"))
        self.notesLabel.setText(_translate("Dialog", "备注:"))
        self.confirmButton.setText(_translate("Dialog", "确认"))
        self.cancelButton.setText(_translate("Dialog", "取消"))
